name: Build Windows EXE


on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pyinstaller scapy requests pandas numpy joblib scikit-learn
      - name: Build EXE
        run: |
          pyinstaller --onefile --clean --name IntelliGuard-Agent ids_windows.py
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: IntelliGuard-Agent
          path: dist/IntelliGuard-Agent.exe
